return {
    EnglishPointer = {
        id = "english_pointer",
        displayName = "Pointer ingles",
        role = "BirdDetection",
        smell = 9,
        speed = 6,
        obedience = 7,
        stamina = 6,
        hunger = 5,
        cost = 500,
        bestCommands = { "Follow", "Search" },
    },
    GermanPointer = {
        id = "german_pointer",
        displayName = "Pointer aleman",
        role = "VersatileTracker",
        smell = 7,
        speed = 8,
        obedience = 7,
        stamina = 7,
        hunger = 6,
        cost = 850,
        bestCommands = { "Follow", "Search" },
    },
    LabradorRetriever = {
        id = "labrador_retriever",
        displayName = "Labrador cobrador",
        role = "Retrieval",
        smell = 6,
        speed = 6,
        obedience = 8,
        stamina = 8,
        hunger = 7,
        cost = 700,
        bestCommands = { "Follow", "Retrieve" },
    },
}
