return {
    Pigeon = {
        id = "pigeon",
        displayName = "Paloma",
        preyType = "Bird",
        sellValue = 20,
        difficulty = 2,
        fleeSpeed = 8,
        idealWeapons = { "slingshot", "shotgun_28" },
        recommendedDog = "english_pointer",
    },
    Duck = {
        id = "duck",
        displayName = "Pato",
        preyType = "Bird",
        sellValue = 45,
        difficulty = 4,
        fleeSpeed = 6,
        idealWeapons = { "shotgun_28", "shotgun_12" },
        recommendedDog = "labrador_retriever",
    },
    Hare = {
        id = "hare",
        displayName = "Liebre",
        preyType = "SmallGame",
        sellValue = 70,
        difficulty = 5,
        fleeSpeed = 8,
        idealWeapons = { "shotgun_12" },
        recommendedDog = "german_pointer",
    },
    Deer = {
        id = "deer",
        displayName = "Ciervo",
        preyType = "BigGame",
        sellValue = 180,
        difficulty = 7,
        fleeSpeed = 5,
        idealWeapons = { "hunting_rifle" },
        recommendedDog = "german_pointer",
    },
    Boar = {
        id = "boar",
        displayName = "Jabali",
        preyType = "BigGame",
        sellValue = 220,
        difficulty = 8,
        fleeSpeed = 7,
        idealWeapons = { "hunting_rifle" },
        recommendedDog = "german_pointer",
    },
}
