return {
    Slingshot = {
        id = "slingshot",
        displayName = "Gomera",
        tier = 1,
        damage = 15,
        range = 25,
        accuracy = 5,
        fireRate = 5,
        cost = 0,
        ammoCost = 0,
        idealPreyTypes = { "Bird", "SmallGame" },
    },
    Shotgun28 = {
        id = "shotgun_28",
        displayName = "Escopeta calibre 28",
        tier = 2,
        damage = 45,
        range = 45,
        accuracy = 5,
        fireRate = 4,
        cost = 350,
        ammoCost = 30,
        idealPreyTypes = { "Bird" },
    },
    Shotgun12 = {
        id = "shotgun_12",
        displayName = "Escopeta calibre 12",
        tier = 3,
        damage = 65,
        range = 50,
        accuracy = 6,
        fireRate = 3,
        cost = 900,
        ammoCost = 55,
        idealPreyTypes = { "Bird", "SmallGame" },
    },
    HuntingRifle = {
        id = "hunting_rifle",
        displayName = "Fusil de caza mayor",
        tier = 4,
        damage = 95,
        range = 120,
        accuracy = 8,
        fireRate = 2,
        cost = 2200,
        ammoCost = 90,
        idealPreyTypes = { "BigGame" },
        smallPreyPenalty = 0.5,
    },
}
